=== MASGAU/MASGAU/Data/data/games.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--simple elements-->
  <xs:element name="title" type="xs:string"/>
  <xs:element name="contributor" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="restore_comment" type="xs:string"/>
  <xs:element name="require_detection" />

  <!--attributes-->

  <xs:attribute name="environment_variable">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="allusersprofile"/>
        <xs:enumeration value="altsavepaths"/>
        <xs:enumeration value="appdata"/>
        <xs:enumeration value="drive"/>
        <xs:enumeration value="flashshared" />
        <xs:enumeration value="installlocation"/>
        <xs:enumeration value="localappdata"/>
        <xs:enumeration value="public"/>
        <xs:enumeration value="savedgames"/>
        <xs:enumeration value="steamuser"/>
        <xs:enumeration value="steamcommon"/>
        <xs:enumeration value="steamsourcemods"/>
        <xs:enumeration value="steamuserdata"/>
        <xs:enumeration value="userprofile"/>
        <xs:enumeration value="userdocuments"/>
        <xs:enumeration value="startmenu" />
        <xs:enumeration value="desktop" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="filename" type="xs:string"/>
  <xs:attribute name="game" type="xs:string"/>
  <xs:attribute name="key" type="xs:string"/>

  <xs:attribute name="region">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="USA"/>
        <xs:enumeration value="EUR"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="name">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[-_A-Za-z0-9]*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="override" default="false" type="xs:boolean" />

  <xs:attribute name="deprecated" type="xs:boolean" />

  <xs:attribute name="path" type="xs:string"/>
  <xs:attribute name="root">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="classes_root"/>
        <xs:enumeration value="current_user"/>
        <xs:enumeration value="current_config"/>
        <xs:enumeration value="dyn_data"/>
        <xs:enumeration value="local_machine"/>
        <xs:enumeration value="performance_data"/>
        <xs:enumeration value="users"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="value" type="xs:string"/>

  <xs:attribute name="platform_version">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="XP"/>
        <xs:enumeration value="Vista"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="date">
    <xs:simpleType>
      <xs:restriction base="xs:string" >
        <xs:pattern value="\d{4}[-](0[1-9]|1[0-2])[-](0[1-9]|[12][0-9]|3[0-2])T([0-1][0-9]|2[0-3])[:][0-5][0-9][:][0-5][0-9]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="platform">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="ScummVM"/>
        <xs:enumeration value="Steam"/>
        <xs:enumeration value="Linux"/>
        <xs:enumeration value="Flash"/>
        <xs:enumeration value="DOS"/>
        <xs:enumeration value="OSX"/>
        <xs:enumeration value="PS1"/>
        <xs:enumeration value="PS2"/>
        <xs:enumeration value="PS3"/>
        <xs:enumeration value="PSP"/>
        <xs:enumeration value="Windows"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Settings"/>
        <xs:enumeration value="Replays"/>
        <xs:enumeration value="MODs"/>
        <xs:enumeration value="Characters"/>
        <xs:enumeration value="Statistics"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <!--attribute groups-->
  <xs:attributeGroup name="playstation_code">
    <xs:attribute name="prefix">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:length value="4"/>
          <xs:pattern value="[A-Z]{4}"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="suffix">
      <xs:simpleType>
        <xs:restriction base="xs:integer" >
          <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  
    <xs:attribute name="append">
      <xs:simpleType>
        <xs:restriction base="xs:string" />
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" type="xs:string"/>

  </xs:attributeGroup>

  <xs:attributeGroup name="location_attributes">
    <xs:attribute ref="platform_version" use="optional"/>
    <xs:attribute ref="deprecated" use="optional"/>
    <xs:attributeGroup ref="append_detract" />
  </xs:attributeGroup>

  <xs:attributeGroup name="append_detract">
    <xs:attribute name="append" type="xs:string"/>
    <xs:attribute name="detract" type="xs:string"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="files">
    <xs:attribute ref="path" use="optional"/>
    <xs:attribute ref="filename" use="optional"/>
    <xs:attribute name="modified_after">
      <xs:simpleType>
        <xs:restriction base="xs:string" >
          <xs:pattern value="\d{4}[-](0[1-9]|1[0-2])[-](0[1-9]|[12][0-9]|3[0-2])T([0-1][0-9]|2[0-3])[:][0-5][0-9][:][0-5][0-9]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="typed_files">
    <xs:attributeGroup ref="files"/>
    <xs:attribute name="type" type="xs:string"/>
  </xs:attributeGroup>


  <!--complex elements-->
  <xs:element name="location_registry">
    <xs:complexType>
      <xs:attribute ref="root" use="required"/>
      <xs:attribute ref="key" use="required"/>
      <xs:attribute ref="value" use="optional"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_shortcut">
    <xs:complexType>
      <xs:attribute ref="environment_variable" use="required"/>
      <xs:attribute ref="path" use="required"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_scummvm">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="location_game">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="platform" use="optional"/>
      <xs:attribute ref="region" use="optional"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_path">
    <xs:complexType>
      <xs:attribute ref="environment_variable" use="required"/>
      <xs:attribute ref="path" use="required"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="save">
    <xs:complexType>
      <xs:attributeGroup ref="typed_files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ignore">
    <xs:complexType>
      <xs:attributeGroup ref="typed_files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ps_code">
    <xs:complexType>
      <xs:attributeGroup ref="playstation_code" />
    </xs:complexType>
  </xs:element>

  <xs:element name="virtualstore">
    <xs:complexType>
      <xs:attribute ref="override" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="identifier">
    <xs:complexType>
      <xs:attributeGroup ref="files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="game">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="1" maxOccurs="1"/>
        <xs:choice>
          <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
              <xs:element ref="location_registry" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_shortcut" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_game" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_path" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_scummvm" minOccurs="1" maxOccurs="unbounded" />
            </xs:choice>
            <xs:element ref="identifier" minOccurs="0" maxOccurs="unbounded"/>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
              <xs:element ref="save" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element ref="ignore" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:element ref="virtualstore" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="require_detection" minOccurs="0" maxOccurs="1"/>
          </xs:sequence>
          <xs:element ref="ps_code" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:element ref="comment" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="restore_comment" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="contributor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="platform" use="optional"/>
      <xs:attribute ref="region" use="optional"/>
      <xs:attribute ref="deprecated" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="games">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="game" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="majorVersion" type="xs:integer" use="required"/>
      <xs:attribute name="minorVersion" type="xs:integer" use="required"/>
      <xs:attribute ref="date" use="required"/>
      <xs:anyAttribute processContents="skip"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MASGAU/MASGAU/Data/Data/ps3.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2011-12-25T00:00:00">
  <!--This file contains PlayStation 3 games-->
  <game name="AssassinsCreed" platform="PS3" region="USA">
    <title>Assassin's Creed</title>
    <ps_code prefix="BLUS" suffix="30089"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="AssassinsCreedBrotherhood" platform="PS3" region="EUR">
    <title>Assassin's Creed: Brotherhood</title>
    <ps_code prefix="BLES" suffix="00909" />
    <contributor>AdmiringWorm</contributor>
  </game>
  <game name="AssassinsCreedRevelations" platform="PS3" region="EUR">
    <title>Assassin's Creed: Revelations</title>
    <ps_code prefix="BLES" suffix="01384"/>
    <contributor>AdmiringWorm</contributor>
  </game>
  <game name="BattlefieldBadcompany" platform="PS3" region="USA">
    <title>Battlefield: Bad Company</title>
    <ps_code prefix="BLUS" suffix="30118"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="BrutalLegend" platform="PS3" region="USA">
    <title>Br√ºtal Legend</title>
    <ps_code prefix="BLUS" suffix="30330"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="CivilizationRevolution" platform="PS3" region="USA">
    <title>Sid Meier's Civilization: Revolution</title>
    <ps_code prefix="BLUS" suffix="30130"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Darkness" platform="PS3" region="USA">
    <title>The Darkness</title>
    <ps_code prefix="BLUS" suffix="30035"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="DeadSpace" platform="PS3" region="USA">
    <title>Dead Space</title>
    <ps_code prefix="BLUS" suffix="30177"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="DevilMayCry4" platform="PS3" region="USA">
    <title>Devil May Cry 4</title>
    <ps_code prefix="BLUS" suffix="30092"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Echochrome" platform="PS3" region="USA">
    <title>Echochrome</title>
    <ps_code prefix="NPUA" suffix="80134"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="ElderScrolls4Oblivion" platform="PS3" region="USA">
    <title>The Elder Scrolls IV: Oblivion</title>
    <ps_code prefix="BLUS" suffix="30007"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Elefunk" platform="PS3" region="USA">
    <title>Elefunk</title>
    <ps_code prefix="NPUA" suffix="80157"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="EternalSonata" platform="PS3" region="USA">
    <title>Eternal Sonata</title>
    <ps_code prefix="BLUS" suffix="30161"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasy13" platform="PS3" region="USA">
    <title>Final Fantasy XIII</title>
    <ps_code prefix="MRTC" suffix="00003"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasy13-2" platform="PS3" region="EUR">
    <title>Final Fantasy XIII-2</title>
    <ps_code prefix="BLES" suffix="01269"/>
    <contributor>AdmiringWorm</contributor>
  </game>
  <game name="Flow" platform="PS3" region="USA">
    <title>Flow</title>
    <ps_code prefix="NPUA" suffix="80001"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Flower" platform="PS3" region="USA">
    <title>Flower</title>
    <ps_code prefix="NPUA" suffix="80083"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Flower" platform="PS3" region="EUR">
    <title>Flower</title>
    <ps_code prefix="NPEA" suffix="00094"/>
    <contributor>AdmiringWorm</contributor>
  </game>
  <game name="Folklore" platform="PS3" region="USA">
    <title>Folklore</title>
    <ps_code prefix="BCUS" suffix="98147"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="HeavenlySword" platform="PS3" region="USA">
    <title>Heavenly Sword</title>
    <ps_code prefix="BCUS" suffix="98132"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="inFamous" platform="PS3" region="USA">
    <title>inFamous</title>
    <ps_code prefix="BCUS" suffix="98119"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="InFamous" platform="PS3" region="EUR">
    <title>inFamous</title>
    <ps_code prefix="BCES" suffix="00609"/>
    <contributor>AdmiringWorm</contributor>
  </game>
  <game name="Jeopardy" platform="PS3" region="USA">
    <title>Jeopardy!</title>
    <ps_code prefix="NPUA" suffix="80227"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Lemmings" platform="PS3" region="USA">
    <title>Lemmings</title>
    <ps_code prefix="NPUA" suffix="80012"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="LuminesSupernova" platform="PS3" region="USA">
    <title>Lumines Supernova</title>
    <ps_code prefix="NPUB" suffix="30048"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="MirrorsEdge" platform="PS3" region="USA">
    <title>Mirror's Edge</title>
    <ps_code prefix="BLUS" suffix="30179"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="PrinceOfPersia2008" platform="PS3" region="USA">
    <title>Prince of Persia (2008)</title>
    <ps_code prefix="BLUS" suffix="30214"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="RagDollKungFuFistsOfPlastic" platform="PS3" region="USA">
    <title>Rag Doll Kung Fu: Fists of Plastic</title>
    <ps_code prefix="NPUA" suffix="80217"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="RatchetClankFutureQuestForBooty" platform="PS3" region="USA">
    <title>Ratchet &amp; Clank Future: Quest For Booty</title>
    <ps_code prefix="NPUA" suffix="80145"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="RatchetClankFutureToolsOfDestruction" platform="PS3" region="USA">
    <title>Ratchet &amp; Clank Future: Tools of Destruction</title>
    <ps_code prefix="BCUS" suffix="98127"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="RedFactionGuerrilla" platform="PS3" region="USA">
    <title>Red Faction: Guerrilla</title>
    <ps_code prefix="BLUS" suffix="30258"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="ResidentEvil5" platform="PS3" region="USA">
    <title>Resident Evil 5</title>
    <ps_code prefix="BLUS" suffix="30270"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Resistance2" platform="PS3" region="USA">
    <title>Resistance 2</title>
    <ps_code prefix="BCUS" suffix="98120"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="ResistanceFallOfMan" platform="PS3" region="USA">
    <title>Resistance: Fall of Man</title>
    <ps_code prefix="BCUS" suffix="98107"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SavageMoon" platform="PS3" region="USA">
    <title>Savage Moon</title>
    <ps_code prefix="NPUA" suffix="80228"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Shatter" platform="PS3" region="USA">
    <title>Shatter</title>
    <ps_code prefix="NPUB" suffix="30091"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SilentHillHomecoming" platform="PS3" region="USA">
    <title>Silent Hill: Homecoming</title>
    <ps_code prefix="BLUS" suffix="30169"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SoulCalibur4" platform="PS3" region="USA">
    <title>Soul Calibur IV</title>
    <ps_code prefix="BLUS" suffix="30160"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SuperStardustHD" platform="PS3" region="USA">
    <title>Super Stardust HD</title>
    <ps_code prefix="NPUA" suffix="80068"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="UltimateAlliance" platform="PS3" region="USA">
    <title>Ultimate Alliance</title>
    <ps_code prefix="BLUS" suffix="30010"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="UnchartedDrakesFortune" platform="PS3" region="USA">
    <title>Uncharted: Drake's Fortune</title>
    <ps_code prefix="BCUS" suffix="98103"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="UnchartedDrakesFortune" platform="PS3" region="EUR">
    <title>Uncharted: Drake's Fortune</title>
    <ps_code prefix="BCES" suffix="00065"/>
    <contributor>AdmiringWorm</contributor>
  </game>
  <game name="UnrealTournament3" platform="PS3" region="USA">
    <title>Unreal Tournament III</title>
    <ps_code prefix="BLUS" suffix="30086"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="ValkyriaChronicles" platform="PS3" region="USA">
    <title>Valkyria Chronicles</title>
    <ps_code prefix="BLUS" suffix="30196"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="ValkyriaChronicles" platform="PS3" region="EUR">
    <title>Valkyria Chronicles</title>
    <ps_code prefix="BLES" suffix="00372"/>
    <contributor>AdmiringWorm</contributor>
  </game>
  <game name="WheelOfFortune" platform="PS3" region="USA">
    <title>Wheel of Fortune</title>
    <ps_code prefix="NPUA" suffix="80137"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Wolfenstein3D" platform="PS3" region="USA">
    <title>Wolfenstein 3D</title>
    <ps_code prefix="NPUB" suffix="30074"/>
    <contributor>SanMadJack</contributor>
  </game>
</games>
