=== MASGAU/MASGAU/Data/data/games.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--simple elements-->
  <xs:element name="title" type="xs:string"/>
  <xs:element name="contributor" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="restore_comment" type="xs:string"/>
  <xs:element name="require_detection" />

  <!--attributes-->

  <xs:attribute name="environment_variable">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="allusersprofile"/>
        <xs:enumeration value="altsavepaths"/>
        <xs:enumeration value="appdata"/>
        <xs:enumeration value="drive"/>
        <xs:enumeration value="flashshared" />
        <xs:enumeration value="installlocation"/>
        <xs:enumeration value="localappdata"/>
        <xs:enumeration value="public"/>
        <xs:enumeration value="savedgames"/>
        <xs:enumeration value="steamuser"/>
        <xs:enumeration value="steamcommon"/>
        <xs:enumeration value="steamsourcemods"/>
        <xs:enumeration value="steamuserdata"/>
        <xs:enumeration value="userprofile"/>
        <xs:enumeration value="userdocuments"/>
        <xs:enumeration value="startmenu" />
        <xs:enumeration value="desktop" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="filename" type="xs:string"/>
  <xs:attribute name="game" type="xs:string"/>
  <xs:attribute name="key" type="xs:string"/>

  <xs:attribute name="region">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="USA"/>
        <xs:enumeration value="EUR"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="name">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[-_A-Za-z0-9]*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="override" default="false" type="xs:boolean" />

  <xs:attribute name="deprecated" type="xs:boolean" />

  <xs:attribute name="path" type="xs:string"/>
  <xs:attribute name="root">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="classes_root"/>
        <xs:enumeration value="current_user"/>
        <xs:enumeration value="current_config"/>
        <xs:enumeration value="dyn_data"/>
        <xs:enumeration value="local_machine"/>
        <xs:enumeration value="performance_data"/>
        <xs:enumeration value="users"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="value" type="xs:string"/>

  <xs:attribute name="platform_version">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="XP"/>
        <xs:enumeration value="Vista"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="date">
    <xs:simpleType>
      <xs:restriction base="xs:string" >
        <xs:pattern value="\d{4}[-](0[1-9]|1[0-2])[-](0[1-9]|[12][0-9]|3[0-2])T([0-1][0-9]|2[0-3])[:][0-5][0-9][:][0-5][0-9]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="platform">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="ScummVM"/>
        <xs:enumeration value="Steam"/>
        <xs:enumeration value="Linux"/>
        <xs:enumeration value="Flash"/>
        <xs:enumeration value="DOS"/>
        <xs:enumeration value="OSX"/>
        <xs:enumeration value="PS1"/>
        <xs:enumeration value="PS2"/>
        <xs:enumeration value="PS3"/>
        <xs:enumeration value="PSP"/>
        <xs:enumeration value="Windows"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Settings"/>
        <xs:enumeration value="Replays"/>
        <xs:enumeration value="MODs"/>
        <xs:enumeration value="Characters"/>
        <xs:enumeration value="Statistics"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <!--attribute groups-->
  <xs:attributeGroup name="playstation_code">
    <xs:attribute name="prefix">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:length value="4"/>
          <xs:pattern value="[A-Z]{4}"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="suffix">
      <xs:simpleType>
        <xs:restriction base="xs:integer" >
          <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  
    <xs:attribute name="append">
      <xs:simpleType>
        <xs:restriction base="xs:string" />
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" type="xs:string"/>

  </xs:attributeGroup>

  <xs:attributeGroup name="location_attributes">
    <xs:attribute ref="platform_version" use="optional"/>
    <xs:attribute ref="deprecated" use="optional"/>
    <xs:attributeGroup ref="append_detract" />
  </xs:attributeGroup>

  <xs:attributeGroup name="append_detract">
    <xs:attribute name="append" type="xs:string"/>
    <xs:attribute name="detract" type="xs:string"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="files">
    <xs:attribute ref="path" use="optional"/>
    <xs:attribute ref="filename" use="optional"/>
    <xs:attribute name="modified_after">
      <xs:simpleType>
        <xs:restriction base="xs:string" >
          <xs:pattern value="\d{4}[-](0[1-9]|1[0-2])[-](0[1-9]|[12][0-9]|3[0-2])T([0-1][0-9]|2[0-3])[:][0-5][0-9][:][0-5][0-9]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="typed_files">
    <xs:attributeGroup ref="files"/>
    <xs:attribute name="type" type="xs:string"/>
  </xs:attributeGroup>


  <!--complex elements-->
  <xs:element name="location_registry">
    <xs:complexType>
      <xs:attribute ref="root" use="required"/>
      <xs:attribute ref="key" use="required"/>
      <xs:attribute ref="value" use="optional"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_shortcut">
    <xs:complexType>
      <xs:attribute ref="environment_variable" use="required"/>
      <xs:attribute ref="path" use="required"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_scummvm">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="location_game">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="platform" use="optional"/>
      <xs:attribute ref="region" use="optional"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_path">
    <xs:complexType>
      <xs:attribute ref="environment_variable" use="required"/>
      <xs:attribute ref="path" use="required"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="save">
    <xs:complexType>
      <xs:attributeGroup ref="typed_files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ignore">
    <xs:complexType>
      <xs:attributeGroup ref="typed_files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ps_code">
    <xs:complexType>
      <xs:attributeGroup ref="playstation_code" />
    </xs:complexType>
  </xs:element>

  <xs:element name="virtualstore">
    <xs:complexType>
      <xs:attribute ref="override" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="identifier">
    <xs:complexType>
      <xs:attributeGroup ref="files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="game">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="1" maxOccurs="1"/>
        <xs:choice>
          <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
              <xs:element ref="location_registry" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_shortcut" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_game" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_path" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_scummvm" minOccurs="1" maxOccurs="unbounded" />
            </xs:choice>
            <xs:element ref="identifier" minOccurs="0" maxOccurs="unbounded"/>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
              <xs:element ref="save" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element ref="ignore" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:element ref="virtualstore" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="require_detection" minOccurs="0" maxOccurs="1"/>
          </xs:sequence>
          <xs:element ref="ps_code" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:element ref="comment" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="restore_comment" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="contributor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="platform" use="optional"/>
      <xs:attribute ref="region" use="optional"/>
      <xs:attribute ref="deprecated" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="games">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="game" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="majorVersion" type="xs:integer" use="required"/>
      <xs:attribute name="minorVersion" type="xs:integer" use="required"/>
      <xs:attribute ref="date" use="required"/>
      <xs:anyAttribute processContents="skip"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MASGAU/MASGAU/Data/data/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2012-01-14T08:40:15">
  <!--Contains profiles for backing up system-related files-->
  <game name="G4WAccountData" platform="Windows">
    <title>Games for Windows Account Data</title>
    <location_path environment_variable="localappdata" path="Microsoft\XLive\Content"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="MASGAUCustomXML">
    <title>MASGAU Custom XML</title>
    <location_path environment_variable="installlocation" path="MASGAU"/>
    <location_registry root="local_machine" key="SOFTWARE\MASGAU" value="InstallPath"/>
    <identifier filename="custom.xml"/>
    <save filename="custom.xml"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="RaptrData" platform="Windows">
    <title>Raptr Data</title>
    <location_path environment_variable="appdata" path="Raptr"/>
    <save path="data"/>
    <save path="Unknown"/>
    <save filename="raptr*"/>
    <ignore filename="*.exe"/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="RGSC" platform="Windows">
    <title>Rockstar Games Social Club</title>
    <location_path environment_variable="localappdata" path="Rockstar Games\RGSC"/>
    <save/>
    <contributor>AvvA</contributor>
  </game>
  <game name="Tomboy">
    <title>Tomboy</title>
    <location_path environment_variable="appdata" path="Tomboy"/>
    <save path="notes"/>
    <save path="config" type="Settings"/>
  </game>
  <game name="UPlayData" platform="Windows">
    <title>UPlay Data</title>
    <location_path environment_variable="installlocation" path="Ubisoft\Ubisoft Game Launcher"/>
    <location_registry root="local_machine" key="SOFTWARE\UbiSoft\Launcher" value="InstallDir"/>
    <save path="storage"/>
    <ignore path="storage\temp"/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="XfireData" platform="Windows">
    <title>Xfire Data</title>
    <location_path environment_variable="allusersprofile" path="Xfire"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
</games>

=== MASGAU/MASGAU/Data/data/!uploadtest.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd"
	majorVersion="1" minorVersion="1"  date="2011-12-25T00:00:00">
  <game name="TesPSGame" platform="PS2">
    <title>Test PS Game</title>
    <ps_code prefix="SLUS" suffix="90210"/>
  </game>
  <game name="TestGame" platform="Windows" region="EUR" deprecated="true">
    <title>Test Game 4</title>
    <location_registry root="local_machine" key="SOFTWARE\Activision\Activenet\Applications\1060.2.1" value="Cwd" append="BLAH"/>
    <location_shortcut environment_variable="startmenu" path="Programs\Titanium\Mercenaries\Play Mercenaries.lnk" detract="splash" deprecated="true"/>
    <location_path environment_variable="installlocation" path="Activision\Titanium\Mercenaries" platform_version="Vista" />
    <location_path environment_variable="installlocation" path="MechVM\games\mw2-mercs-tt" platform_version="XP"/>
    <location_game name="TesPSGame" platform="PS2"/>
    <identifier path="mek"/>
    <save path="mek" type="Mechs" />
    <save filename="userstar.bwd" />
    <save filename="MW2PRM.CFG" type="Settings" modified_after="1923-12-01T12:00:00" />
    <save filename="MW2REG.CFG" type="Settings" />
    <ignore path="temp"/>
    <ignore path="temp2" type="seteter"/>
    <virtualstore override="true" />
    <require_detection />
    <comment>This is a comment</comment>
    <restore_comment>This is a restore comment</restore_comment>
    <contributor>SanMadJack</contributor>
  </game>
</games>

=== MASGAU/MASGAU/Data/Data/steam.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2011-12-25T00:00:00">
  <!--This file contains games whose saves are only compatible with Steam releases of the game-->
  <game name="AlienSwarm" platform="Steam">
    <title>Alien Swarm</title>
    <location_path environment_variable="steamuserdata" path="630"/>
    <save/>
    <contributor>AvvA</contributor>
  </game>
  <game name="AnomalyWarzoneEarth" platform="Steam">
    <title>Anomaly: Warzone Earth</title>
    <location_path environment_variable="steamuserdata" path="91200" />
    <save />
    <contributor>Arc Angel</contributor>
  </game>
  <game name="Bastion" platform="Steam">
    <title>Bastion</title>
    <location_path environment_variable="steamuserdata" path="107100"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="Braid" platform="Steam">
    <title>Braid</title>
    <location_path environment_variable="steamuserdata" path="26800"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Brink" platform="Steam">
    <title>Brink</title>
    <location_path environment_variable="steamuserdata" path="22350"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="CallOfJuarezTheCartel" platform="Steam">
    <title>Call of Juarez: The Cartel</title>
    <location_path environment_variable="steamuserdata" path="33420\remote\out" />
    <save />
    <contributor>Arc Angel</contributor>
  </game>
  <game name="Civilization5" platform="Steam">
    <title>Sid Meier's Civilization V</title>
    <location_path environment_variable="steamuserdata" path="8930"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="DeadIsland" platform="Steam">
    <title>Dead Island</title>
    <location_path environment_variable="steamuserdata" path="91310"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="DefenseGridTheAwakening" platform="Steam">
    <title>Defense Grid: The Awakening</title>
    <location_path environment_variable="steamuserdata" path="18500"/>
    <save/>
    <contributor>AvvA</contributor>
  </game>
  <game name="DeusExHumanRevolution" platform="Steam">
    <title>Deus Ex: Human Revolution</title>
    <location_path environment_variable="steamuserdata" path="28050"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="DeusExHumanRevolutionTheMissingLink" platform="Steam">
    <title>Deus Ex: Human Revolution - The Missing Link</title>
    <location_path environment_variable="steamuserdata" path="201280"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="DocClockTheToastedSandwichOfTime" platform="Steam">
    <title>Doc Clock: The Toasted Sandwich of Time</title>
    <location_path environment_variable="steamuserdata" path="57800"/>
    <save/>
    <contributor>AvvA</contributor>
  </game>
  <game name="DukeNukemForever" platform="Steam">
    <title>Duke Nukem Forever</title>
    <location_path environment_variable="steamuserdata" path="57900"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="FEAR3" platform="Steam">
    <title>F.3.A.R.</title>
    <location_path environment_variable="steamuserdata" path="21100"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="FlightControlHD" platform="Steam">
    <title>Flight Control HD</title>
    <location_path environment_variable="steamuserdata" path="62000"/>
    <save/>
    <contributor>AvvA</contributor>
  </game>
  <game name="FrontMissionEvolved" platform="Steam">
    <title>Front Mission Evolved</title>
    <location_path environment_variable="steamuserdata" path="43000"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="HydrophobiaProphecy" platform="Steam">
    <title>Hydrophobia: Prophecy</title>
    <location_path environment_variable="steamuserdata" path="92000"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="JustCause2" platform="Steam">
    <title>Just Cause 2</title>
    <location_path environment_variable="steamuserdata" path="8190"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="LaraCroftAndTheGuardianOfLight" platform="Steam">
    <title>Lara Croft and the Guardian of Light</title>
    <location_path environment_variable="steamuserdata" path="35130" deprecated="true"/>
    <location_path environment_variable="steamuserdata" path="35150"/>
    <save/>
    <contributor>Arc Angel</contributor>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Limbo" platform="Steam">
    <title>Limbo</title>
    <location_path environment_variable="steamuserdata" path="48000"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="MonkeyIsland2SpecialEditionLeChucksRevenge" platform="Steam">
    <title>Monkey Island 2 Special Edition: LeChucks Revenge</title>
    <location_path environment_variable="steamuserdata" path="32460"/>
    <save/>
    <contributor>slake_jones</contributor>
  </game>
  <game name="PoundOfGround" platform="Steam">
    <title>Pound of Ground</title>
    <location_path environment_variable="steamuserdata" path="33980"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="Psychonauts" platform="Steam">
    <title>Psychonauts</title>
    <location_path environment_variable="steamuserdata" path="3830"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Quantz" platform="Steam">
    <title>Quantz</title>
    <location_path environment_variable="steamuserdata" path="37800"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="RedFactionArmageddon" platform="Steam">
    <title>Red Faction: Armageddon</title>
    <location_path environment_variable="steamuserdata" path="55110"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="RevengeOfTheTitans" platform="Steam">
    <title>Revenge of the Titans</title>
    <location_path environment_variable="steamuserdata" path="93200\remote\.revenge_of_the_titans_1.80"/>
    <save/>
    <contributor>AdmiringWorm</contributor>
  </game>
  <game name="RunespellOverture" platform="Steam">
    <title>Runespell: Overture</title>
    <location_path environment_variable="steamuserdata" path="102200"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="SeriousSamHD1" platform="Steam">
    <title>Serious Sam HD: The First Encounter</title>
    <location_path environment_variable="steamuserdata" path="41000\local\SeriousSamHD"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SeriousSamHD2" platform="Steam">
    <title>Serious Sam HD: The Second Encounter</title>
    <location_path environment_variable="steamuserdata" path="41010\local\SeriousSamHD_TSE"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="SeriousSam3BFE" platform="Steam">
    <title>Serious Sam 3: BFE</title>
    <location_path environment_variable="steamuserdata" path="41070\local" />
    <save />
    <contributor>Arc Angel</contributor>
  </game>
  <game name="Shank" platform="Steam">
    <title>Shank</title>
    <location_path environment_variable="steamuserdata" path="6120"/>
    <save/>
    <contributor>Arc Angel</contributor>
  </game>
  <game name="Trine" platform="Steam">
    <title>Trine</title>
    <location_path environment_variable="steamuserdata" path="35700"/>
    <save/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Warhammer40kDawnOfWar2Retribution" platform="Steam">
    <title>Warhammer 40,000: Dawn of War II - Retribution</title>
    <location_path environment_variable="steamuserdata" path="56400" />
    <save />
    <contributor>AvvA</contributor>
  </game>
  <game name="Warhammer40kSpaceMarine" platform="Steam">
    <title>Warhammer 40,000: Space Marine</title>
    <location_path environment_variable="steamuserdata" path="55150\remote" />
    <save />
    <contributor>Arc Angel</contributor>
  </game>
</games>

=== MASGAU/MASGAU/Data/Data/flash.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2011-12-25T00:00:00">
  <!--This file contains games that are based on Flash-->
  <game name="CodenameGordon" platform="Flash">
    <title>Codename: Gordon</title>
    <location_path environment_variable="appdata" path="Macromedia\Flash Player\localhost"/>
    <save filename="hl2d_settings.sol" type="Settings"/>
    <contributor>AvvA</contributor>
  </game>
  <game name="Machinarium" platform="Flash">
    <title>Machinarium</title>
    <location_path environment_variable="flashshared" path="localhost\steam\steamapps\common\machinarium"/>
    <save/>
    <contributor>AvvA</contributor>
  </game>
  <game name="VVVVVV" platform="Flash">
    <title>VVVVVV</title>
    <location_path environment_variable="flashshared" path="localhost\steam\steamapps\common\VVVVVV"/>
    <save/>
    <contributor>AvvA</contributor>
  </game>
</games>

=== MASGAU/MASGAU/Data/Data/games.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2011-12-25T00:00:00">
  <!--This file contains games that have saves that are compatible with more than one platform-->
  <game name="Altitude">
    <title>Altitude</title>
    <location_path environment_variable="steamcommon" path="Altitude"/>
    <save path="config" type="Settings"/>
    <contributor>AvvA</contributor>
  </game>
  <game name="DontTakeItPersonallyBabeItJustAintYourStory">
    <title>don't take it personally, babe, it just ain't your story</title>
    <location_path environment_variable="appdata" path="RenPy\digital2-1298756237"/>
    <save/>
  </game>
  <game name="fs2_open">
    <title>fs2_open</title>
    <location_path environment_variable="installlocation" path="fs2_open"/>
    <location_game name="FreeSpace2" platform="Windows"/>
    <identifier filename="fs2_open*"/>
    <save path="data\players"/>
    <comment>Doesn't have a default install folder, so might require an Alt. Install Path.</comment>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="UrQuanMasters">
    <title>The Ur-Quan Masters</title>
    <location_path environment_variable="appdata" path="uqm"/>
    <location_path environment_variable="userprofile" path=".uqm"/>
    <save path="save"/>
    <save filename="*.cfg" type="Settings"/>
    <contributor>Scandalon</contributor>
  </game>
</games>

=== MASGAU/MASGAU/Data/data/ps1.xml
<?xml version="1.0" encoding="UTF-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2012-01-14T08:40:15">
  <!--This file contains PlayStation games-->
  <game name="ChronoCross" platform="PS1" region="USA">
    <title>Chrono Cross</title>
    <ps_code prefix="SLUS" suffix="01041"/>
    <ps_code prefix="SLUS" suffix="01080"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="ChronoTrigger" platform="PS1" region="USA">
    <title>Chrono Trigger</title>
    <ps_code prefix="SLUS" suffix="01363"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Descent" platform="PS1" region="USA">
    <title>Descent</title>
    <ps_code prefix="SLUS" suffix="00037"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="DescentMaximum" platform="PS1" region="USA">
    <title>Descent: Maximum</title>
    <ps_code prefix="SLUS" suffix="00460"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FearEffect" platform="PS1" region="USA">
    <title>Fear Effect</title>
    <ps_code prefix="SLUS" suffix="00920"/>
    <ps_code prefix="SLUS" suffix="01056"/>
    <ps_code prefix="SLUS" suffix="01057"/>
    <ps_code prefix="SLUS" suffix="01058"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FearEffect2" platform="PS1" region="USA">
    <title>Fear Effect 2: Retro Helix</title>
    <ps_code prefix="SLUS" suffix="01266"/>
    <ps_code prefix="SLUS" suffix="01275"/>
    <ps_code prefix="SLUS" suffix="01276"/>
    <ps_code prefix="SLUS" suffix="01277"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasy4" platform="PS1" region="USA">
    <title>Final Fantasy IV</title>
    <ps_code prefix="SLUS" suffix="01360"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasy7" platform="PS1" region="USA">
    <title>Final Fantasy VII</title>
    <ps_code prefix="SCUS" suffix="94163"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasy8" platform="PS1" region="USA">
    <title>Final Fantasy VIII</title>
    <ps_code prefix="SLUS" suffix="00892"/>
    <ps_code prefix="SLUS" suffix="00908"/>
    <ps_code prefix="SLUS" suffix="00909"/>
    <ps_code prefix="SLUS" suffix="00910"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasy9" platform="PS1" region="USA">
    <title>Final Fantasy IX</title>
    <ps_code prefix="SLUS" suffix="01251"/>
    <ps_code prefix="SLUS" suffix="01295"/>
    <ps_code prefix="SLUS" suffix="01296"/>
    <ps_code prefix="SLUS" suffix="01297"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasyTactics" platform="PS1" region="USA">
    <title>Final Fantasy Tactics</title>
    <ps_code prefix="SLUS" suffix="94221"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="MetalGearSolid" platform="PS1" region="USA">
    <title>Metal Gear Solid</title>
    <ps_code prefix="SLUS" suffix="00594"/>
    <ps_code prefix="SLUS" suffix="00776"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="MetalGearSolidVRMissions" platform="PS1" region="USA">
    <title>Metal Gear Solid: VR Missions</title>
    <ps_code prefix="SLUS" suffix="00957"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="ParasiteEve" platform="PS1" region="USA">
    <title>Parasite Eve</title>
    <ps_code prefix="SLUS" suffix="00662"/>
    <ps_code prefix="SLUS" suffix="00668"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="ParasiteEve2" platform="PS1" region="USA">
    <title>Parasite Eve II</title>
    <ps_code prefix="SLUS" suffix="01042"/>
    <ps_code prefix="SLUS" suffix="01055"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SilentHill" platform="PS1" region="USA">
    <title>Silent Hill</title>
    <ps_code prefix="SLUS" suffix="00707"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SoulBlade" platform="PS1" region="USA">
    <title>Soul Blade</title>
    <ps_code prefix="SLUS" suffix="00240"/>
    <contributor>SanMadJack</contributor>
  </game>
</games>
