=== MASGAU/MASGAU/Data/data/games.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--simple elements-->
  <xs:element name="title" type="xs:string"/>
  <xs:element name="contributor" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="restore_comment" type="xs:string"/>
  <xs:element name="require_detection" />

  <!--attributes-->

  <xs:attribute name="environment_variable">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="allusersprofile"/>
        <xs:enumeration value="altsavepaths"/>
        <xs:enumeration value="appdata"/>
        <xs:enumeration value="drive"/>
        <xs:enumeration value="flashshared" />
        <xs:enumeration value="installlocation"/>
        <xs:enumeration value="localappdata"/>
        <xs:enumeration value="public"/>
        <xs:enumeration value="savedgames"/>
        <xs:enumeration value="steamuser"/>
        <xs:enumeration value="steamcommon"/>
        <xs:enumeration value="steamsourcemods"/>
        <xs:enumeration value="steamuserdata"/>
        <xs:enumeration value="userprofile"/>
        <xs:enumeration value="userdocuments"/>
        <xs:enumeration value="startmenu" />
        <xs:enumeration value="desktop" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="filename" type="xs:string"/>
  <xs:attribute name="game" type="xs:string"/>
  <xs:attribute name="key" type="xs:string"/>

  <xs:attribute name="region">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="USA"/>
        <xs:enumeration value="EUR"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="name">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[-_A-Za-z0-9]*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="override" default="false" type="xs:boolean" />

  <xs:attribute name="deprecated" type="xs:boolean" />

  <xs:attribute name="path" type="xs:string"/>
  <xs:attribute name="root">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="classes_root"/>
        <xs:enumeration value="current_user"/>
        <xs:enumeration value="current_config"/>
        <xs:enumeration value="dyn_data"/>
        <xs:enumeration value="local_machine"/>
        <xs:enumeration value="performance_data"/>
        <xs:enumeration value="users"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="value" type="xs:string"/>

  <xs:attribute name="platform_version">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="XP"/>
        <xs:enumeration value="Vista"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="date">
    <xs:simpleType>
      <xs:restriction base="xs:string" >
        <xs:pattern value="\d{4}[-](0[1-9]|1[0-2])[-](0[1-9]|[12][0-9]|3[0-2])T([0-1][0-9]|2[0-3])[:][0-5][0-9][:][0-5][0-9]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="platform">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="ScummVM"/>
        <xs:enumeration value="Steam"/>
        <xs:enumeration value="Linux"/>
        <xs:enumeration value="Flash"/>
        <xs:enumeration value="DOS"/>
        <xs:enumeration value="OSX"/>
        <xs:enumeration value="PS1"/>
        <xs:enumeration value="PS2"/>
        <xs:enumeration value="PS3"/>
        <xs:enumeration value="PSP"/>
        <xs:enumeration value="Windows"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Settings"/>
        <xs:enumeration value="Replays"/>
        <xs:enumeration value="MODs"/>
        <xs:enumeration value="Characters"/>
        <xs:enumeration value="Statistics"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <!--attribute groups-->
  <xs:attributeGroup name="playstation_code">
    <xs:attribute name="prefix">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:length value="4"/>
          <xs:pattern value="[A-Z]{4}"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="suffix">
      <xs:simpleType>
        <xs:restriction base="xs:integer" >
          <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  
    <xs:attribute name="append">
      <xs:simpleType>
        <xs:restriction base="xs:string" />
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" type="xs:string"/>

  </xs:attributeGroup>

  <xs:attributeGroup name="location_attributes">
    <xs:attribute ref="platform_version" use="optional"/>
    <xs:attribute ref="deprecated" use="optional"/>
    <xs:attributeGroup ref="append_detract" />
  </xs:attributeGroup>

  <xs:attributeGroup name="append_detract">
    <xs:attribute name="append" type="xs:string"/>
    <xs:attribute name="detract" type="xs:string"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="files">
    <xs:attribute ref="path" use="optional"/>
    <xs:attribute ref="filename" use="optional"/>
    <xs:attribute name="modified_after">
      <xs:simpleType>
        <xs:restriction base="xs:string" >
          <xs:pattern value="\d{4}[-](0[1-9]|1[0-2])[-](0[1-9]|[12][0-9]|3[0-2])T([0-1][0-9]|2[0-3])[:][0-5][0-9][:][0-5][0-9]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="typed_files">
    <xs:attributeGroup ref="files"/>
    <xs:attribute name="type" type="xs:string"/>
  </xs:attributeGroup>


  <!--complex elements-->
  <xs:element name="location_registry">
    <xs:complexType>
      <xs:attribute ref="root" use="required"/>
      <xs:attribute ref="key" use="required"/>
      <xs:attribute ref="value" use="optional"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_shortcut">
    <xs:complexType>
      <xs:attribute ref="environment_variable" use="required"/>
      <xs:attribute ref="path" use="required"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_scummvm">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="location_game">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="platform" use="optional"/>
      <xs:attribute ref="region" use="optional"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_path">
    <xs:complexType>
      <xs:attribute ref="environment_variable" use="required"/>
      <xs:attribute ref="path" use="required"/>
      <xs:attributeGroup ref="location_attributes" />
    </xs:complexType>
  </xs:element>

  <xs:element name="save">
    <xs:complexType>
      <xs:attributeGroup ref="typed_files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ignore">
    <xs:complexType>
      <xs:attributeGroup ref="typed_files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ps_code">
    <xs:complexType>
      <xs:attributeGroup ref="playstation_code" />
    </xs:complexType>
  </xs:element>

  <xs:element name="virtualstore">
    <xs:complexType>
      <xs:attribute ref="override" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="identifier">
    <xs:complexType>
      <xs:attributeGroup ref="files" />
    </xs:complexType>
  </xs:element>

  <xs:element name="game">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="1" maxOccurs="1"/>
        <xs:choice>
          <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
              <xs:element ref="location_registry" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_shortcut" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_game" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_path" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_scummvm" minOccurs="1" maxOccurs="unbounded" />
            </xs:choice>
            <xs:element ref="identifier" minOccurs="0" maxOccurs="unbounded"/>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
              <xs:element ref="save" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element ref="ignore" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:element ref="virtualstore" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="require_detection" minOccurs="0" maxOccurs="1"/>
          </xs:sequence>
          <xs:element ref="ps_code" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:element ref="comment" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="restore_comment" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="contributor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="platform" use="optional"/>
      <xs:attribute ref="region" use="optional"/>
      <xs:attribute ref="deprecated" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="games">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="game" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="majorVersion" type="xs:integer" use="required"/>
      <xs:attribute name="minorVersion" type="xs:integer" use="required"/>
      <xs:attribute ref="date" use="required"/>
      <xs:anyAttribute processContents="skip"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MASGAU/MASGAU/Data/data/mods.xml
<?xml version="1.0" encoding="UTF-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2012-01-14T08:40:15">
  <!--This file contains mods for other games-->
  <game name="CinematicMod10HL2" platform="Windows">
    <title>Cinematic Mod 10 (Half-Life 2 Mod)</title>
    <location_path environment_variable="steamsourcemods" path="FAKEFACTORY_CM10\hl2"/>
    <save path="SAVE"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="CinematicMod10HL2Ep1" platform="Windows">
    <title>Cinematic Mod 10 (Half-Life 2: Episode 1 Mod)</title>
    <location_path environment_variable="steamsourcemods" path="FAKEFACTORY_CM10\episodic"/>
    <save path="SAVE"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="CinematicMod10HL2Ep2" platform="Windows">
    <title>Cinematic Mod 10 (Half-Life 2: Episode 2 Mod)</title>
    <location_path environment_variable="steamsourcemods" path="FAKEFACTORY_CM10\ep2"/>
    <save path="SAVE"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Flesh" platform="Windows">
    <title>Flesh (Source Mod)</title>
    <location_path environment_variable="steamsourcemods" path="Flesh"/>
    <save path="SAVE"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="NamelessMod" platform="Windows">
    <title>The Nameless Mod (Deus Ex Mod)</title>
    <location_shortcut environment_variable="startmenu" path="Programs\The Nameless Mod\The Nameless Mod.lnk" append="TNM" detract="System"/>
    <location_game name="DeusEx" platform="Windows" append="TNM"/>
    <save path="System" filename="*.ini" type="Settings"/>
    <save path="Save"/>
    <contributor>Trestkon</contributor>
  </game>
  <game name="ResearchAndDevelopment" platform="Windows">
    <title>Research and Development (Source Mod)</title>
    <location_path environment_variable="steamsourcemods" path="Research and Development"/>
    <save path="SAVE"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="TitanXCIX1" platform="Steam">
    <title>Titan: XCIX - Part 1</title>
    <location_path environment_variable="steamsourcemods" path="SurvivorIZ"/>
    <save path="SAVE"/>
    <contributor>Arc Angel</contributor>
  </game>
</games>

=== MASGAU/MASGAU/Data/Data/scummvm.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2011-12-25T00:00:00">
  <!--This file contains games that are run through the ScummVM project-->
  <game name="BeneathASteelSky" platform="ScummVM">
    <title>Beneath a Steel Sky</title>
    <location_path environment_variable="installlocation" path="GOG.com\Beneath a Steel Sky"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGBENEATH" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Beneath a Steel Sky\Beneath a Steel Sky.lnk" detract="ScummVM"/>
    <save filename="SKY-VM.*"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="BrokenSword1" platform="ScummVM">
    <title>Broken Sword: The Shadow of the Templars</title>
    <location_path environment_variable="installlocation" path="GOG.com\Broken Sword - The Shadow of the Templars"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGBROKENSWORD1" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Broken Sword - The Shadow of the Templars\Broken Sword - The Shadow of the Templars\Broken Sword - The Shadow of the Templars.lnk" detract="ScummVM"/>
    <save filename="sword1.*"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="BrokenSword2" platform="ScummVM">
    <title>Broken Sword II: The Smoking Mirror</title>
    <location_path environment_variable="installlocation" path="GOG.com\Broken Sword II - The Smoking Mirror"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGBROKENSWORD2" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Broken Sword II - The Smoking Mirror\Broken Sword II - The Smoking Mirror.lnk" detract="ScummVM"/>
    <save filename="bsword2.*"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FeebleFiles" platform="ScummVM">
    <title>The Feeble Files</title>
    <location_path environment_variable="installlocation" path="GOG.com\The Feeble Files"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGFEBBLEFILES" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\The Feeble Files\The Feeble Files.lnk" detract="ScummVM"/>
    <save filename="feeble.0??"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Gobliins2" platform="ScummVM">
    <title>Gobliins 2</title>
    <location_path environment_variable="installlocation" path="GOG.com\Gobliiins Pack\Gobliins2"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGGOBLINS2" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Gobliiins Pack\Gobliiins\Gobliiins.lnk" append="Gobliins2" detract="ScummVM"/>
    <save filename="gobliins2.*"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Gobliins2Floppy" platform="ScummVM">
    <title>Gobliins 2 Floppy</title>
    <location_path environment_variable="installlocation" path="GOG.com\Gobliiins Pack\Gobliins2 Floppy"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGGOBLINS2FDD" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Gobliiins Pack\Gobliiins\Gobliiins (Floppy Verion).lnk" append="Gobliins2 Floppy" detract="ScummVM"/>
    <save filename="gobliins2FDD.*"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="GoblinsQuest3" platform="ScummVM">
    <title>Goblins Quest 3</title>
    <location_path environment_variable="installlocation" path="GOG.com\Gobliiins Pack\Goblins3"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGGOBLINS3" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Gobliiins Pack\Goblins Quest 3\Goblins Quest 3.lnk" append="Goblins3" detract="ScummVM"/>
    <save filename="goblins3.*"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="GoblinsQuest3Floppy" platform="ScummVM">
    <title>Goblins Quest 3 Floppy</title>
    <location_path environment_variable="installlocation" path="GOG.com\Gobliiins Pack\Goblins3 Floppy"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGGOBLINS3FDD" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Gobliiins Pack\Goblins Quest 3\Goblins Quest 3 (Floppy Verion).lnk" append="Goblins3 Floppy" detract="ScummVM"/>
    <save filename="goblins3FDD.*"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="LureOfTheTemptress" platform="ScummVM">
    <title>Lure of the Temptress</title>
    <location_path environment_variable="installlocation" path="GOG.com\Lure of the Temptress"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGLURE" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Lure of the Temptress\Lure of the Temptress.lnk"/>
    <save filename="lure.*"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SimonTheSorcerer" platform="ScummVM">
    <title>Simon the Sorcerer</title>
    <location_path environment_variable="installlocation" path="GOG.com\Simon the Sorcerer"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGSIMON" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Simon the Sorcerer\Simon the Sorcerer.lnk" detract="ScummVM"/>
    <save filename="simon1.0*"/>
    <save filename="simon1.ini" type="Settings"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SimonTheSorcerer2" platform="ScummVM">
    <title>Simon the Sorcerer 2</title>
    <location_path environment_variable="installlocation" path="GOG.com\Simon the Sorcerer 2"/>
    <location_registry root="local_machine" key="SOFTWARE\GOG.com\GOGSIMON2" value="PATH"/>
    <location_shortcut shortcut="Programs\GOG.com\Simon the Sorcerer 2\Simon the Sorcerer 2.lnk" detract="ScummVM"/>
    <save filename="simon2.0*"/>
    <save filename="simon2.ini" type="Settings"/>
    <contributor>SanMadJack</contributor>
  </game>
</games>

=== MASGAU/MASGAU/Data/Data/ps1.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="1" date="2011-12-25T00:00:00">
  <!--This file contains PlayStation games-->
  <game name="ChronoCross" platform="PS1" country="USA">
    <title>Chrono Cross</title>
    <ps_code prefix="SLUS" suffix="01041"/>
    <ps_code prefix="SLUS" suffix="01080"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="ChronoTrigger" platform="PS1" country="USA">
    <title>Chrono Trigger</title>
    <ps_code prefix="SLUS" suffix="01363"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="Descent" platform="PS1" country="USA">
    <title>Descent</title>
    <ps_code prefix="SLUS" suffix="00037"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="DescentMaximum" platform="PS1" country="USA">
    <title>Descent: Maximum</title>
    <ps_code prefix="SLUS" suffix="00460"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="FearEffect" platform="PS1" country="USA">
    <title>Fear Effect</title>
    <ps_code prefix="SLUS" suffix="00920"/>
    <ps_code prefix="SLUS" suffix="01056"/>
    <ps_code prefix="SLUS" suffix="01057"/>
    <ps_code prefix="SLUS" suffix="01058"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="FearEffect2" platform="PS1" country="USA">
    <title>Fear Effect 2: Retro Helix</title>
    <ps_code prefix="SLUS" suffix="01266"/>
    <ps_code prefix="SLUS" suffix="01275"/>
    <ps_code prefix="SLUS" suffix="01276"/>
    <ps_code prefix="SLUS" suffix="01277"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="FinalFantasy4" platform="PS1" country="USA">
    <title>Final Fantasy IV</title>
    <ps_code prefix="SLUS" suffix="01360"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="FinalFantasy7" platform="PS1" country="USA">
    <title>Final Fantasy VII</title>
    <ps_code prefix="SCUS" suffix="94163"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="FinalFantasy8" platform="PS1" country="USA">
    <title>Final Fantasy VIII</title>
    <ps_code prefix="SLUS" suffix="00892"/>
    <ps_code prefix="SLUS" suffix="00908"/>
    <ps_code prefix="SLUS" suffix="00909"/>
    <ps_code prefix="SLUS" suffix="00910"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="FinalFantasy9" platform="PS1" country="USA">
    <title>Final Fantasy IX</title>
    <ps_code prefix="SLUS" suffix="01251"/>
    <ps_code prefix="SLUS" suffix="01295"/>
    <ps_code prefix="SLUS" suffix="01296"/>
    <ps_code prefix="SLUS" suffix="01297"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="FinalFantasyTactics" platform="PS1" country="USA">
    <title>Final Fantasy Tactics</title>
    <ps_code prefix="SLUS" suffix="94221"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="MetalGearSolid" platform="PS1" country="USA">
    <title>Metal Gear Solid</title>
    <ps_code prefix="SLUS" suffix="00594"/>
    <ps_code prefix="SLUS" suffix="00776"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="MetalGearSolidVRMissions" platform="PS1" country="USA">
    <title>Metal Gear Solid: VR Missions</title>
    <ps_code prefix="SLUS" suffix="00957"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="ParasiteEve" platform="PS1" country="USA">
    <title>Parasite Eve</title>
    <ps_code prefix="SLUS" suffix="00662"/>
    <ps_code prefix="SLUS" suffix="00668"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="ParasiteEve2" platform="PS1" country="USA">
    <title>Parasite Eve II</title>
    <ps_code prefix="SLUS" suffix="01042"/>
    <ps_code prefix="SLUS" suffix="01055"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="SilentHill" platform="PS1" country="USA">
    <title>Silent Hill</title>
    <ps_code prefix="SLUS" suffix="00707"/>
    <contributer>SanMadJack</contributer>
  </game>
  <game name="SoulBlade" platform="PS1" country="USA">
    <title>Soul Blade</title>
    <ps_code prefix="SLUS" suffix="00240"/>
    <contributer>SanMadJack</contributer>
  </game>
</games>

=== MASGAU/MASGAU/Data/Data/psp.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games.xsd" majorVersion="1" minorVersion="2" date="2011-12-25T00:00:00">
  <!--This file contains PSP (PlayStation Portable) games-->
  <game name="BraveStoryNewTraveler" platform="PSP" region="USA">
    <title>Brave Story: New Traveler</title>
    <ps_code prefix="ULUS" suffix="10279"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="CrisisCoreFinalFantasy7" platform="PSP" region="USA">
    <title>Crisis Core: Final Fantasy VII</title>
    <ps_code prefix="ULUS" suffix="10336"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Daxter" platform="PSP" region="USA">
    <title>Daxter</title>
    <ps_code prefix="UCUS" suffix="98618"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="DissidiaFinalFantasy" platform="PSP" region="USA">
    <title>Dissidia: Final Fantasy</title>
    <ps_code prefix="ULUS" suffix="10437"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Echochrome" platform="PSP" region="USA">
    <title>Echochrome</title>
    <ps_code prefix="NPUG" suffix="80135"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasy" platform="PSP" region="USA">
    <title>Final Fantasy</title>
    <ps_code prefix="ULUS" suffix="10251"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasy2" platform="PSP" region="USA">
    <title>Final Fantasy II</title>
    <ps_code prefix="ULUS" suffix="10263"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="FinalFantasyTacticsWarOfTheLions" platform="PSP" region="USA">
    <title>Final Fantasy Tactics: War of the Lions</title>
    <ps_code prefix="ULUS" suffix="10297"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="GodOfWarChainsOfOlympus" platform="PSP" region="USA">
    <title>God of War: Chains of Olympus</title>
    <ps_code prefix="UCUS" suffix="98653"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="GrandTheftAutoChinatownWars" platform="PSP" region="EUR">
    <title>Grand Theft Auto: Chinatown Wars</title>
    <ps_code prefix="ULES" suffix="01347"/>
    <contributor>duncans_pumpkin</contributor>
  </game>
  <game name="GrandTheftAutoLibertyCityStories" platform="PSP" region="EUR">
    <title>Grand Theft Auto: Liberty City Stories</title>
    <ps_code prefix="ULES" suffix="00151"/>
    <contributor>duncans_pumpkin</contributor>
  </game>
  <game name="GrandTheftAutoViceCityStories" platform="PSP" region="USA">
    <title>Grand Theft Auto: Vice City Stories</title>
    <ps_code prefix="ULUS" suffix="10160"/>
    <contributor>duncans_pumpkin</contributor>
  </game>
  <game name="JeanneDArc" platform="PSP" region="USA">
    <title>Jeanne D'Arc</title>
    <ps_code prefix="UCUS" suffix="98700"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Lumines" platform="PSP" region="EUR">
    <title>Lumines</title>
    <ps_code prefix="ULES" suffix="00043"/>
    <contributor>duncans_pumpkin</contributor>
  </game>
  <game name="MetalGearAcid" platform="PSP" region="USA">
    <title>Metal Gear Ac!d</title>
    <ps_code prefix="ULUS" suffix="10006"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="MetalGearAcid" platform="PSP" region="EUR">
    <title>Metal Gear Ac!d</title>
    <ps_code prefix="ULES" suffix="00008"/>
    <contributor>duncans_pumpkin</contributor>
  </game>
  <game name="MetalGearAcid2" platform="PSP" region="EUR">
    <title>Metal Gear Ac!d 2</title>
    <ps_code prefix="ULES" suffix="00284"/>
    <contributor>duncans_pumpkin</contributor>
  </game>
  <game name="MetalGearSolidPortableOps" platform="PSP" region="USA">
    <title>Metal Gear Solid: Portable Ops</title>
    <ps_code prefix="ULUS" suffix="10202"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="NoGravity" platform="PSP" region="USA">
    <title>No Gravity</title>
    <ps_code prefix="NPUH" suffix="10007"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="Patapon" platform="PSP" region="USA">
    <title>Patapon</title>
    <ps_code prefix="UCUS" suffix="98711"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="RatchetClankSizeMatters" platform="PSP" region="USA">
    <title>Ratchet &amp; Clank: Size Matters</title>
    <ps_code prefix="UCUS" suffix="98633"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SilentHill0rigins" platform="PSP" region="USA">
    <title>Silent Hill: 0rigins</title>
    <ps_code prefix="ULUS" suffix="10285"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="StarOceanFirstDeparture" platform="PSP" region="USA">
    <title>Star Ocean: First Departure</title>
    <ps_code prefix="ULUS" suffix="10374"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="SuperStardustPortable" platform="PSP" region="USA">
    <title>Super Stardust Portable</title>
    <ps_code prefix="NPUG" suffix="80221"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="TombRaiderLegend" platform="PSP" region="EUR">
    <title>Tomb Raider: Legend</title>
    <ps_code prefix="ULES" suffix="00283"/>
    <contributor>SanMadJack</contributor>
  </game>
  <game name="WipeoutPure" platform="PSP" region="EUR">
    <title>Wipeout Pure</title>
    <ps_code prefix="UCES" suffix="00001"/>
    <contributor>duncans_pumpkin</contributor>
  </game>
</games>
